### PR TITLE
Added Russian translation. I think it would be interesting for everyone, not only for Englishspeakers.

### PR DESCRIPTION
**Pull request by xmalinov**
I'll be glad for any corrections to the translation.

### CODE REVIEW

**Comment by jamiebuilds** [comment]
I can set this repo up with crowdin if you want to do this.

**Comment by xmalinov** [comment]
It would be nice, but as I know crowdin isn't free, even for opensource and something like that.

**Comment by hzoo** [comment]
James has set it up on the other repos like https://github.com/thejameskyle/babel-handbook 😄 

https://crowdin.com/page/open-source-project-setup-request

**Comment by xmalinov** [comment]
So, I guess it would be really nice to set it up.

**Comment by jamiebuilds** [comment]
I know how to make shit happen

**Comment by jamiebuilds** [comment]
The repo is now set up to be translated, you can see instructions over here: https://github.com/thejameskyle/documentation-handbook/blob/master/CONTRIBUTING.md

**Comment by xmalinov** [comment]
Moved the translation to the Crowdin project. And made some typo fixes there.

**Comment by jamiebuilds** [comment]
Awesome, it was synced back to the repo. Thanks!

**Pull request closed without merging**
